name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: syj0002012/myweather
          stage: main
          yaml: >
            name: my-weather-v1-0

            app: java@17

            options:
              ports: 8080
              jarfile: weather-spring/build/libs/weather-spring-0.0.1-SNAPSHOT.jar
              env:
                - name: DB_HOST
                  value: mariadb
                - name: DB_PORT
                  value: "3306"
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: DB_NAME
                  value: ${{ secrets.DB_NAME }}
                - name: KAKAO_API_KEY
                  value: ${{ secrets.KAKAO_API_KEY }}
                - name: DATA_API_KEY
                  value: ${{ secrets.DATA_API_KEY }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
